/**
 * Created by 罗志伟 on 2017/2/22.
 */
export const COM_NAV_STATUS = 'COM_NAV_STATUS'
export const COM_INIT_INDEX = 'COM_INIT_INDEX'
export const COM_LOADING_STATUS = 'COM_LOADING_STATUS'
export const GET_SEARCH_KEY = 'GET_SEARCH_KEY'
export const GET_PAGE_NUM = 'GET_PAGE_NUM'
export const GET_SCORLL_STATUS = 'GET_SCORLL_STATUS'
export const GET_TOPICS_LIST = 'GET_TOPICS_LIST'
export const GET_TOPICS_DETAIL = 'GET_TOPICS_DETAIL'
export const GET_USER_DATA = 'GET_USER_DATA'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_LOGIN_STATUS = 'SET_LOGIN_STATUS'
export const GET_MESSAGE_LIST = 'GET_MESSAGE_LIST'
export const COM_HEADER_STATUS = 'COM_HEADER_STATUS'
